Feat/#45 apply coupon
highVTest/E-Commerce pull request #48
Opened 2024-07-24 15:58 UTC by Ppajingae

## 요약
> 쿠폰 결제 시에 적용

## 작업 사항

> 결제 시에 쿠폰 적용 로직 추가
> 환불 요청 시 쿠폰 반환 로직 추가
> 쿠폰 삭제 로직은 추후에 Spring Batch 등을 통해서 추가 할 예정

## 리뷰 요청 사항(선택)

---
### 해결한 이슈
closes: #45

2024-07-24 16:10 UTC, Ppajingae commented
쿠폰 유효시간 만료 로직은 사실 DB에서 거를 수도 있는 부분이긴 한데 Exception으로 추가하는 것이 좋다고 생각이 들어서 추가했습니다

2024-07-25 06:07 UTC, HifumiAlice requested changes
주문시 details에 상품 정보 등록 후 장바구니에서 상품들 지우기 필수

2024-07-25 06:25 UTC, Ppajingae commented
@HifumiAlice 다시 확인 부탁드립니다

2024-07-25 06:38 UTC, HifumiAlice approved these changes
확인 했습니다.

2024-07-25 07:30 UTC, HifumiAlice reviewed
확인해주세요

2024-07-25 07:30 UTC, HifumiAlice commented on src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponToBuyerJpaRepository.kt
> +    fun findAllByCouponIdAndBuyerIdAndIsUsedFalse(couponId: List<Long>, buyerId: Long): List<CouponToBuyer>
Jpa 함수명으로 이용하는데 Query로 날리는 이유는 무엇인가요?

2024-07-25 07:30 UTC, HifumiAlice commented on src/main/kotlin/com/highv/ecommerce/domain/item_cart/repository/ItemCartRepository.kt
> +    fun findAllByIdAndBuyerId(id: ArrayList<Long>, buyerId: Long): List<ItemCart>
이 부분도 JPA 메소드 안 쓰고 Query로 하는 이유가 있나요?

2024-07-25 07:30 UTC, HifumiAlice commented on src/main/kotlin/com/highv/ecommerce/domain/order_details/service/OrderDetailsService.kt
> +        val orderDetails = orderDetailsRepository.findAllByShopIdAndBuyerId(shopId, buyerId)
주문 id 구분 없이 shop_id만 같으면 다 불러오지 않나요? 때문에 order_id로 구분해줘야 할 거 같습니다.

2024-07-25 07:53 UTC, Ppajingae commented on src/main/kotlin/com/highv/ecommerce/domain/order_details/service/OrderDetailsService.kt
> +        val orderDetails = orderDetailsRepository.findAllByShopIdAndBuyerId(shopId, buyerId)
큰 문제 아니라서 업데이트 하였습니다

2024-07-25 07:54 UTC, Ppajingae commented on src/main/kotlin/com/highv/ecommerce/domain/item_cart/repository/ItemCartRepository.kt
> +    fun findAllByIdAndBuyerId(id: ArrayList<Long>, buyerId: Long): List<ItemCart>
이 부분은 조금 더 봐야 할 것 같습니다 지금 상황으론 변수에 List 값을 주면 맵핑이 안되는 것 같습니다

2024-07-25 08:20 UTC, merged