Feat/#58 Implement Admin Backoffice Test Code
highVTest/E-Commerce pull request #64
Opened 2024-07-27 17:29 UTC by 1hyung

## 요약
> 간단 요약
Admin Backoffice Test Code입니다.

## 작업 사항
Admin Backoffice Test Code입니다.
BehaviorSpec을 사용하여 Given When Then구문으로 작성하려고 했습니다.

> PR에서 작업한 사항들을 적어주세요(이미지, 스크린샷등을 활용해도 좋아요)

## 리뷰 요청 사항(선택)

> 리뷰시 봐주었으면 하는 부분이 있다면 적어주세요
테스트코드 작성이 매우 미흡합니다. 확인 부탁드립니다.

---
### 해결한 이슈
closes: #58

2024-07-27 18:32 UTC, HifumiAlice requested changes
다른 부분은 다 괜찮은데 shop/ blacklist capture하는 부분이 문제가 있으니 꼭 수정해주세요!!

2024-07-27 18:32 UTC, HifumiAlice commented on src/test/kotlin/com/highv/ecommerce/backoffice/AdminBackOfficeServiceTest.kt
> +            every { blackListRepository.save(capture(blackListSlot)) } returns blackListSlot.captured
returns에는 blackListSlot.captured가 아닌 blacklist 객체를 만들어서 반환해야합니다.

2024-07-27 18:32 UTC, HifumiAlice commented on src/test/kotlin/com/highv/ecommerce/backoffice/AdminBackOfficeServiceTest.kt
> +            every { blackListRepository.save(capture(blackListSlot)) } returns blackListSlot.captured
returns에는 blackListSlot.captured가 아닌 blacklist 객체를 만들어서 반환해야합니다.

2024-07-27 18:32 UTC, HifumiAlice commented on src/test/kotlin/com/highv/ecommerce/backoffice/AdminBackOfficeServiceTest.kt
> +                every { this@mockk.sellerId } returns sellerId
이 부분 shop이 목킹이 아니라서 안되는 거 같습니다. shop을 만들어서 직접 넣는 형식으로 해야할 거 같아요

2024-07-27 18:32 UTC, HifumiAlice commented on src/test/kotlin/com/highv/ecommerce/backoffice/AdminBackOfficeServiceTest.kt
> +        When("블랙리스트 항목이 존재하면") {
존재하지 않는 경우도 추가했으면 좋을 거 같습니다.

2024-07-27 18:32 UTC, HifumiAlice commented on src/test/kotlin/com/highv/ecommerce/backoffice/AdminBackOfficeServiceTest.kt
> +    Given("관리자가 블랙리스트 항목을 삭제할 때") {
given이랑 when의 순서가 반대인 거 같습니다.
Given(항목이 존재해서) When(관리자가 삭제하면) Then(삭제된다)가 맞는 거 같습니다.

2024-07-28 00:18 UTC, 1hyung commented on src/test/kotlin/com/highv/ecommerce/backoffice/AdminBackOfficeServiceTest.kt
> +            every { blackListRepository.save(capture(blackListSlot)) } returns blackListSlot.captured
감사합니다!

2024-07-28 00:19 UTC, 1hyung commented on src/test/kotlin/com/highv/ecommerce/backoffice/AdminBackOfficeServiceTest.kt
> +            every { blackListRepository.save(capture(blackListSlot)) } returns blackListSlot.captured
감사합니다!

2024-07-28 00:21 UTC, 1hyung commented on src/test/kotlin/com/highv/ecommerce/backoffice/AdminBackOfficeServiceTest.kt
> +                every { this@mockk.sellerId } returns sellerId
감사합니다! 변경했습니다!

2024-07-28 00:56 UTC, 1hyung commented on src/test/kotlin/com/highv/ecommerce/backoffice/AdminBackOfficeServiceTest.kt
> +        When("블랙리스트 항목이 존재하면") {
단건 조회와 삭제 존재하지 않는 경우 추가했습니다!

2024-07-28 00:59 UTC, 1hyung commented on src/test/kotlin/com/highv/ecommerce/backoffice/AdminBackOfficeServiceTest.kt
> +    Given("관리자가 블랙리스트 항목을 삭제할 때") {
블랙리스트 삭제에서 Given에서 항목이 존재하지 않으면 테스트코드 자체가 필요없으니까 When(항목이 존재하지 않을 경우) 작성했던 코드는 삭제했습니다!

2024-07-28 01:04 UTC, 1hyung commented on src/test/kotlin/com/highv/ecommerce/backoffice/AdminBackOfficeServiceTest.kt
> +    Given("관리자가 블랙리스트 항목을 삭제할 때") {
테스트 순서 변경했습니다! 
확인 부탁드립니다! 
늦은 시간까지 정말 고생 많으셨습니다 크흡
건강 절대 지켜~~

2024-07-28 04:26 UTC, HifumiAlice approved these changes
크게 문제 있어 보이진 않습니다.

2024-07-28 05:28 UTC, Ppajingae approved these changes
테스트 코드가 본인이 원하는 대로 작동 되었다면 크게 문제되지 않을 것 같습니다 고생하셨습니다

2024-07-28 05:29 UTC, merged